In [1]:
import torch

In [2]:
# Check if GPU is available
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

Using device: cuda


In [3]:
# Create a tensor on CPU
cpu_tensor = torch.rand(3, 3)
print("Tensor on CPU:")
print(cpu_tensor)

Tensor on CPU:
tensor([[0.5608, 0.5423, 0.1808],
        [0.7690, 0.7802, 0.6115],
        [0.0273, 0.6613, 0.1080]])


In [4]:
# Move the tensor to GPU
gpu_tensor = cpu_tensor.to(device)
print("Tensor on GPU:")
print(gpu_tensor)

Tensor on GPU:
tensor([[0.5608, 0.5423, 0.1808],
        [0.7690, 0.7802, 0.6115],
        [0.0273, 0.6613, 0.1080]], device='cuda:0')


In [5]:
# Perform some operations on GPU
result_tensor = gpu_tensor + 2
print("Result Tensor on GPU:")
print(result_tensor)

Result Tensor on GPU:
tensor([[2.5608, 2.5423, 2.1808],
        [2.7690, 2.7802, 2.6115],
        [2.0273, 2.6613, 2.1080]], device='cuda:0')


In [6]:
# Check GPU utilization
gpu_memory_allocated = torch.cuda.memory_allocated(device)
gpu_memory_cached = torch.cuda.memory_reserved(device)
print(f"GPU Memory Allocated: {gpu_memory_allocated / 1024**3:.2f} GB")
print(f"GPU Memory Cached: {gpu_memory_cached / 1024**3:.2f} GB")

GPU Memory Allocated: 0.00 GB
GPU Memory Cached: 0.00 GB
